# Standalone mode
listen=YES
listen_ipv6=NO

# Security
anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=022

# Chroot
chroot_local_user=YES
allow_writeable_chroot=YES
secure_chroot_dir=/var/run/vsftpd/empty

# Passive mode
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110
pasv_address=127.0.0.1

# Logging
xferlog_enable=YES
xferlog_std_format=YES
log_ftp_protocol=YES

# User settings
user_sub_token=$USER
local_root=/var/www/wordpress

dual_log_enable=YES
vsftpd_log_file=/var/log/vsftpd.log